# application.yml
spring:
  application:
    name: discovery-service
  config:
    import: optional:configserver:http://10.0.0.7:8889

server:
  port: 8761

eureka:
  instance:
    hostname: discovery-service
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://10.0.1.37:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always