apiVersion: v1
kind: ConfigMap
metadata:
  name: discovery-config
  namespace: discovery
data:
  spring.profiles.active: "prod"
  application.yml: |
    server:
      port: 8761
    eureka:
      client:
        registerWithEureka: false
        fetchRegistry: false
      server:
        waitTimeInMsWhenSyncEmpty: 0