apiVersion: v1
kind: ConfigMap
metadata:
  name: discovery-service-config
  namespace: fintech
data:
  application.yml: |-
    spring:
      application:
        name: discovery-service
      config:
        import: optional:configserver:http://config-service:8889
    
    server:
      port: 8761
