apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service-deploy
  namespace: fintech
spec:
  replicas: 1  # Only one replica as it's a singleton service
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: public.ecr.aws/z1z0w2y6/discovery-service:latest
          ports:
            - containerPort: 8761
          envFrom:
            - configMapRef:
                name: discovery-service-config
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 60
            periodSeconds: 15