apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: discovery
spec:
  type: ClusterIP
  ports:
    - port: 8761
      targetPort: 8761
      protocol: TCP
  selector:
    app: discovery-service